### ISSUE TITLE
Fetch Course Info failed

### ISSUE THREAD

**Issue by JohnSmith5412** [cristminix/LLFetcher#3]
https://www.linkedin.com/learning/project-management-international-projects/improve-your-global-project-results?u=2720425

I am trying to download this course [using the pre-release version](https://github.com/cristminix/LLFetcher/releases/tag/3.0%2B-rev). However, it is not working (see below screenshot)

<img width="1224" alt="Screenshot 2023-12-12 at 14 37 33" src="https://github.com/cristminix/LLFetcher/assets/153623750/22848775-884f-440e-8d3e-cdc48e6970a4">

<img width="1509" alt="Screenshot 2023-12-12 at 14 38 21" src="https://github.com/cristminix/LLFetcher/assets/153623750/b72bdc17-2e74-4e67-8416-05f1c5a66dfe">

Similarly, with [the latest version](https://github.com/cristminix/LLFetcher/releases/tag/3.0-beta), it is also not working (see screenshot below). The logs say it is due to an issue with the slug - can't find it! I think it's the same error with the pre-release version above. 

<img width="1493" alt="Screenshot 2023-12-12 at 14 40 14" src="https://github.com/cristminix/LLFetcher/assets/153623750/ce9cd115-2ba4-4a15-bd4b-42adbdaced17">

<img width="641" alt="Screenshot 2023-12-12 at 14 41 12" src="https://github.com/cristminix/LLFetcher/assets/153623750/6fc70cd0-497c-4ad1-9000-c1bcddb4e369">

Could you help me fix that please? 

Thank you for your work! It's really great and very useful 🙏

**Comment by cristminix** [comment]
Sorry for reply too late, we just update pre-release the latest nightly build,  [dist-3.0.1-dev.zip](https://github.com/cristminix/LLFetcher/releases/download/3.0.1-dev/dist-3.0.1-dev.zip) 

don't forget to remove previous version and load unpacked again, thank you bro.

**Comment by JohnSmith5412** [comment]
Thanks for your help bro! I removed the previous version and loaded unpacked again. 
Unfortunately I still get some errors:

1. ReferenceError: getCourseInfo is not defined
<img width="666" alt="Screenshot 2023-12-14 at 09 50 32" src="https://github.com/cristminix/LLFetcher/assets/153623750/48ff7816-d497-4cbc-9ab3-30721c4d222a">

2. Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
<img width="667" alt="Screenshot 2023-12-14 at 09 51 04" src="https://github.com/cristminix/LLFetcher/assets/153623750/34a41cf6-6c23-41e8-8f55-f4cf6730bd2b">

Still on this url: https://www.linkedin.com/learning/project-management-international-projects/improve-your-global-project-results?u=2720425

Got any ideas bro? 
Again, huge thanks for your work and for looking into my issue

**Comment by cristminix** [comment]
ooh i'am not sure about this issues but i just can testing on my windows 10 machine and have no problems 
![Capture](https://github.com/cristminix/LLFetcher/assets/48685260/e8516b06-5178-4ed9-b4a7-cc4bb83942b3)
