### ISSUE TITLE
Run Queue Setup > Get Available Media Format & Subtitle > Infinite Loading

### ISSUE THREAD

**Issue by AffonsoS** [cristminix/LLFetcher#8]
Errors on console:
![image](https://github.com/cristminix/LLFetcher/assets/8432537/80d7331a-50e1-43bd-a1f4-96ec973eadf2)
![image](https://github.com/cristminix/LLFetcher/assets/8432537/e111e7d5-463f-40ef-a71b-8a23c0e1f311)

**Comment by AffonsoS** [comment]
to show some context, this is happening while i am trying to download in this Learn Courses: https://www.linkedin.com/learning/paths/learn-css, only this specific one so far is happening to have this bug: https://www.linkedin.com/learning/css-selectors-2/the-power-of-selectors-23420115

**Comment by cristminix** [comment]
thank you for posting, about `css-selectors-2` we forget to check for the course that doesn't have caption or transcript,

**Comment by AffonsoS** [comment]
it does have caption tho, or am i tripping perhaps

**Comment by cristminix** [comment]
we have update nightly build release please check if it has been fixed thanks

**Comment by AffonsoS** [comment]
it has worked pretty well, thank u so much. however, just out of curiosity, how come is it impossible to download any CC at all including the default american english one if they are still available on the course itself?
